package hello.hellospring.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Member {

    // Id : PK 매핑
    // PK(Id 컬럼)은 DB에서 직접 값을 생성해 주고 있음
    /*
    * create table member
    (
     id bigint generated by default as identity,
     name varchar(255),
     primary key (id)
    );
    *
    * 이렇게 insert into member(name) values('hong'); 을 해도 자동으로 id값 생성되는 상태
    *
    * */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // 만약 변수명이 DB에 저장된 컬럼명과 상이할 경우 @Column(name = "username") 이런 식으로 변경
    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
