/*Q1*/

SELECT * FROM FAMNT0201TMI WHERE EAI_INTF_PRG_STS_CD = 'N' AND EAI_DATA_SEQ ='202107090925560000001'ORDER BY EAI_DATA_SEQ  ASC;

UPDATE FAMNT0201TMI SET EAI_TR_DT=SYSDATE , EAI_INTF_PRG_STS_CD='Y' WHERE EAI_DATA_SEQ ='202107090925560000001';


SELECT * FROM FAMNT0201TMI;

SELECT EAI_TR_DT,EAI_INS_CD,EAI_DATA_SEQ,ITEM_CD,APLD_ST_DT,ITEM_HAN_NM,ITEM_ENG_NM,ITEM_HAN_SNM,ITEM_ENG_SNM,PRD_CD,EVL_TP_CD,MKPR_EVL_CYC_CD,ENT_AST_EVL_MTH_CD,ISSUE_INS_WHRB_NTN_CD,CURR_CD,STKEX_CD,ISSUE_INS_CD,UNT_AMT,IMC_CD,FUND_CD,IMC_FUND_CD,NPS_FUND_CD,FUND_MG_CD,CUTY_INS_CD,RDMN_YN,CTAC_DT,MTY_DT,RDMN_DT,FEE_PYM_CYC_MCNT,BCRT_INS_CD,ACTNO,CTFC_NO,APLD_END_DT,EXTL_INF_CLS_STD_ID,EAI_SNR_DS_CD,EAI_VRF_YN,EAI_PCS_SQ,EAI_INTF_PRG_STS_CD,EAI_PCS_DTTM,EAI_LOD_DTTM,EAI_APLC_PCS_DTTM,EAI_CRUD_CD,EAI_CLS_DT,ATH_PRCS_NO,ATH_STS_CD,CRTN_USR_ID,CRTN_DTTM,WRK_USR_ID,WRK_DTTM,WRKR_IP
FROM FAMNT0201TMI;

/*Q2*/

SELECT EAI_TR_DT,EAI_INS_CD,EAI_DATA_SEQ,ITEM_CD,APLD_ST_DT,ITEM_HAN_NM,ITEM_ENG_NM,ITEM_HAN_SNM,ITEM_ENG_SNM,PRD_CD,EVL_TP_CD,MKPR_EVL_CYC_CD,ENT_AST_EVL_MTH_CD,ISSUE_INS_WHRB_NTN_CD,CURR_CD,STKEX_CD,ISSUE_INS_CD,UNT_AMT,IMC_CD,FUND_CD,IMC_FUND_CD,NPS_FUND_CD,FUND_MG_CD,CUTY_INS_CD,RDMN_YN,CTAC_DT,MTY_DT,RDMN_DT,FEE_PYM_CYC_MCNT,BCRT_INS_CD,ACTNO,CTFC_NO,APLD_END_DT,EXTL_INF_CLS_STD_ID,EAI_SNR_DS_CD,EAI_VRF_YN,EAI_PCS_SQ,EAI_INTF_PRG_STS_CD,EAI_PCS_DTTM,EAI_LOD_DTTM,EAI_APLC_PCS_DTTM,EAI_CRUD_CD,EAI_CLS_DT,ATH_PRCS_NO,ATH_STS_CD,CRTN_USR_ID,CRTN_DTTM,WRK_USR_ID,WRK_DTTM,WRKR_IP
FROM FAMNT0201TMI WHERE EAI_INTF_PRG_STS_CD = 'N' AND EAI_TR_DT IN('20210903','22/08/04','20211119');

/*Q3*/
SELECT EAI_TR_DT,EAI_INS_CD,EAI_DATA_SEQ,ITEM_CD,APLD_ST_DT,ITEM_HAN_NM,ITEM_ENG_NM,ITEM_HAN_SNM,ITEM_ENG_SNM,PRD_CD,EVL_TP_CD,MKPR_EVL_CYC_CD,ENT_AST_EVL_MTH_CD,ISSUE_INS_WHRB_NTN_CD,CURR_CD,STKEX_CD,ISSUE_INS_CD,UNT_AMT,IMC_CD,FUND_CD,IMC_FUND_CD,NPS_FUND_CD,FUND_MG_CD,CUTY_INS_CD,RDMN_YN,CTAC_DT,MTY_DT,RDMN_DT,FEE_PYM_CYC_MCNT,BCRT_INS_CD,ACTNO,CTFC_NO,APLD_END_DT,EXTL_INF_CLS_STD_ID,EAI_SNR_DS_CD,EAI_VRF_YN,EAI_PCS_SQ,EAI_INTF_PRG_STS_CD,EAI_PCS_DTTM,EAI_LOD_DTTM,EAI_APLC_PCS_DTTM,EAI_CRUD_CD,EAI_CLS_DT,ATH_PRCS_NO,ATH_STS_CD,CRTN_USR_ID,CRTN_DTTM,WRK_USR_ID,WRK_DTTM,WRKR_IP
FROM FAMNT0201TMI WHERE EAI_INTF_PRG_STS_CD = 'N' AND EAI_TR_DT IN('20210903','22/08/04','20211119');

SELECT TO_CHAR(EAI_TR_DT) FROM FAMNT0201TMI;



